// figma node: 2757:10805 .grid (4 variants)
const __venc = (v) => String(v).replace(/[%|=]/g, encodeURIComponent);
const __vkey = (p) => "type=" + __venc(p.type);

export function Grid(_p = {}) {
  const props = { ..._p, type: _p.type ?? "12col" };
  const __body0 = () => (
    <div className={props.className} style={{
      width: 1280,
      height: 800,
      position: "relative",
      ...props.style,
    }}>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 40,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 142,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 244,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 346,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 448,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 550,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 652,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 754,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 856,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 958,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1060,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1162,
        top: 0,
        width: 78,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 118,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 220,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 322,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 424,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 526,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 628,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 730,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 832,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 934,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1036,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1138,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1240,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
    </div>
  );
  const __body1 = () => (
    <div className={props.className} style={{
      width: 1600,
      height: 800,
      position: "relative",
      ...props.style,
    }}>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 40,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 170,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 300,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 430,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 560,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 690,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 820,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 950,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1080,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1210,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1340,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1470,
        top: 0,
        width: 90,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 130,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 260,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 390,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 520,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 650,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 780,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 910,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1040,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1170,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1300,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1430,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 1560,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
    </div>
  );
  const __body2 = () => (
    <div className={props.className} style={{
      width: 768,
      height: 800,
      position: "relative",
      ...props.style,
    }}>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 40,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 129,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 218,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 307,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 396,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 485,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 574,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 663,
        top: 0,
        width: 65,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 105,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 194,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 283,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 372,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 461,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 550,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 639,
        top: 0,
        width: 24,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 728,
        top: 0,
        width: 40,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
    </div>
  );
  const __body3 = () => (
    <div className={props.className} style={{
      width: 320,
      height: 800,
      position: "relative",
      ...props.style,
    }}>
      <div style={{
        position: "absolute",
        left: 0,
        top: 0,
        width: 8,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 8,
        top: 0,
        width: 64,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 88,
        top: 0,
        width: 64,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 168,
        top: 0,
        width: 64,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 248,
        top: 0,
        width: 64,
        height: 800,
        backgroundColor: "rgba(255,101,151,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 72,
        top: 0,
        width: 16,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 152,
        top: 0,
        width: 16,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 232,
        top: 0,
        width: 16,
        height: 800,
        backgroundColor: "rgba(0,230,255,0.4)",
      }} />
      <div style={{
        position: "absolute",
        left: 312,
        top: 0,
        width: 8,
        height: 800,
        backgroundColor: "rgba(0,254,93,0.4)",
      }} />
    </div>
  );
  const __impls = {
    // figma: type=12col
    "type=12col": __body0,
    // figma: type=tv12col
    "type=tv12col": __body1,
    // figma: type=8col
    "type=8col": __body2,
    // figma: type=4col
    "type=4col": __body3,
  };
  return (__impls[__vkey(props)] ?? __body0)();
}
export default Grid;
